parameters:
    region: '%env(AWS_REGION)%'
    aws_key: '%env(AWS_KEY)%'
    aws_secret: '%env(AWS_SECRET)%'
    aws_sns_arn: '%env(AWS_SNS_ARN)%'
    aws_sns_arn_dev: '%env(AWS_SNS_ARN_DEV)%'

aws:
    version: latest
    region: '%region%'
    credentials:
        key: '%aws_key%'
        secret: '%aws_secret%'
    ec2: 
        region: '%region%'
        version: '2016-11-15'
    S3:
        version: '2006-03-01'

services:
    aws.credentials:
        class: Aws\Credentials\Credentials
        public: true
        arguments:
            - '%aws_key%'
            - '%aws_secret%'

    app.aws:
        class: App\Service\AwsService
        public: true
        arguments: 
            - '@service_container'
            - '@aws.ec2'
            
#    aws.ec2:
#        class: Aws\Ec2\Ec2Client
#        public: true
#        arguments: 
#            - { region: 'eu-west-3', version: 'latest', credentials: '@aws.credentials' }
